version: '3.4'

services:
  taskify.webapi:
    image: ${DOCKER_REGISTRY-}taskifywebapi
    build:
      context: .
      dockerfile: Taskify.WebAPI/Dockerfile
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment: 
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=Admin@123
        - MSSQL_PID=DEVELOPER
        - MSSQL_TCP_PORT=1433
    ports:
        - "1455:1433"
    
  

